version: 0.2
phases:
  install:
    runtime-versions:
      java: 8
  build:
    commands:
      - export BUCKET=aws-sam-cli-managed-default-samclisourcebucket-pjrx39t7k26r
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
      - mvn install
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml