version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - aws s3 mb s3://new-create-pipeline-bucket
      - sam build
  post_build:
    commands:
      - aws s3 sync ./build s3://new-create-pipeline-bucket
