version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - export BUCKET=pipeline-lambda-demo
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
      - mvn install
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yml